export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

export enum AuthStatusCode {
  AUTHENTICATION_REQUIRED = HttpStatusCode.UNAUTHORIZED,
  INVALID_TOKEN = HttpStatusCode.UNAUTHORIZED,
  TOKEN_EXPIRED = HttpStatusCode.UNAUTHORIZED,
  INSUFFICIENT_PERMISSIONS = HttpStatusCode.FORBIDDEN
}

export enum GatewayStatusCode {
  GATEWAY_HEALTHY = HttpStatusCode.OK,
  ROUTE_NOT_FOUND = HttpStatusCode.NOT_FOUND,
  SERVICE_UNAVAILABLE = HttpStatusCode.SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT = HttpStatusCode.GATEWAY_TIMEOUT
}
